import { IApiCatalogFlat } from '../store/api/apiTypes';

let flat: IApiCatalogFlat = {
    area: 140.77,
    attributes: {
        balcony: true,
        bath: true,
        cornerGlazing: false,
        dressingRoom: true,
        finish: false,
        frenchBalcony: false,
        highCeiling: true,
        laundry: false,
        livingKitchen: false,
        loggia: false,
        masterBedroom: true,
        panoramicGlazing: false,
        woWhitebox: true,
        whiteBox: false,
    },
    floor: 14,
    guid: '82a6b533-df20-40f7-b855-8f41f55f5c94',
    has_advertising_price: 0,
    id: 829624,
    houseName: 'reds',
    mainBenefit: {
        benefitPrice: 85859423,
        description: 'тест',
        discount: null,
        discountPercent: null,
        guid: '8f6876bb-e96f-ed11-85dc-0050568d7c58',
        id: 135165,
        isFamily: false,
        isMain: true,
        isReplacingStandardPrice: false,
        maxPrice: null,
        mortgage: null,
        name: 'Тест Republic (наличные)',
        priceMeter: 609927,
    },
    number: '115',
    price: '85 859 423',
    real_price: 85859423,
    currentPrice: 85859423,
    rooms: 4,
    layout: {
        flat_plan_png: '',
    },
    bulk: {
        building_status: 59,
        houseName: 'Reds',
        id: 8996,
        keyDate: 'string;',
        name: 'string;',
        number: 10,
        settlement_date: 'string',
        settlement_quarter: 1,
        settlement_year: 1,
    },
    section: { id: 20908, number: 1, floorsCount: 26 },
    status: 'free',
    bookingStatus: 'reserve',
    bulk_id: 8996,
    similar: [],
    redPrice: false,
};

export { flat };

let redPriceFlat = {
    area: 140.77,
    attributes: {
        balcony: true,
        bath: true,
        cornerGlazing: false,
        dressingRoom: true,
        finish: false,
        frenchBalcony: false,
        highCeiling: true,
        laundry: false,
        livingKitchen: false,
        loggia: false,
        masterBedroom: true,
        panoramicGlazing: false,
        woWhitebox: true,
        whiteBox: true,
    },
    floor: 14,
    guid: '82a6b533-df20-40f7-b855-8f41f55f5c94',
    has_advertising_price: 0,
    id: 829624,
    layout: {
        flat_plan_png: '',
    },
    mainBenefit: {
        benefitPrice: 85859423,
        description: 'тест',
        discount: null,
        discountPercent: null,
        guid: '8f6876bb-e96f-ed11-85dc-0050568d7c58',
        id: 135165,
        isFamily: false,
        isMain: true,
        isReplacingStandardPrice: false,
        maxPrice: null,
        mortgage: null,
        name: 'Тест Republic (наличные)',
        priceMeter: 609927,
    },
    bulk: {
        building_status: 59,
        houseName: 'Reds',
        id: 8996,
        keyDate: 'string;',
        name: 'string;',
        number: 10,
        settlement_date: 'string',
        settlement_quarter: 1,
        settlement_year: 1,
    },
    houseName: 'reds',
    number: '115',
    price: '85 859 423',
    real_price: 85859423,
    currentPrice: 85859423,
    rooms: 4,
    section: { id: 20908, number: 1, floorsCount: 26 },
    status: 'free',
    bulk_id: 8996,
    similar: [],
    redPrice: true,
    bookingStatus: 'reserve',
};

export { redPriceFlat };
