import { ComponentStory, ComponentMeta } from '@storybook/react';
import SvgIcons, { ISvgIcons } from './SvgIcons';
import { Provider } from 'react-redux';
import { store } from '../../store/reduxStore';
import React from 'react';

export default {
    title: 'SVG/SvgIcons',
    component: SvgIcons,
    // More on argTypes: https://storybook.js.org/docs/react/api/argtypes
    argTypes: {
        id: {
            type: 'string',
            description: 'Список используемых иконок',
            defaultValue: 'whiteBox',
            options: [
                'whiteBox',
                'woWhitebox',
                'highCeiling',
                'balcony',
                'frenchBalcony',
                'bath',
                'bathrooms',
                'laundry',
                'countOfBathrooms',
                'masterBedroom',
                'roomOnEast',
                'roomOnNorth',
                'roomOnSouth',
                'roomOnWest',
                'cornerGlazing',
                'fireplace',
                'livingKitchen',
                'panoramicGlazing',
                'patio',
                'penthouse',
                'vidNaReku',
                'sauna',
                'terrace',
                'vidVoDvor',
                'vidNaPark',
                'dressingRoom',
                'oknaNa2Storony',
                'oknaNa3Storony',
                'oknaNa1Storony',
                'cabinet',
                'loggia',
                'bath',
                'heart in a circle',
                'PDF in a circle',
                'tel in a circle',
                'arrow next dark small',
                'arrow next dark medium',
                'arrow next light small',
                'arrow next transparent small',
                'arrow next transparent small light hover',
                'arrow next transparent small light',
                'arrow prev transparent small',
                'arrow prev transparent small light hover',
                'arrow prev transparent small light',
                'arrow up dark medium',
                'arrow up transparent medium',
                'arrow up outline medium',
                'arrow down outline medium',
                'arrow up transparent dark',
                'arrow up transparent light',
                'arrow prev dark stroke medium',
                'arrow next dark stroke medium',
                'arrow prev dark stroke medium div',
                'arrow next dark stroke medium div',
                'arrow next stroke large',
                'arrow prev stroke large',
                'arrow prev light large',
                'arrow next light large',
                'arrow down transparent dark',
                'arrow down transparent light',
                'arrow down light',
                'arrow down dark',
                'arrow next dark large',
                'arrows-scroll',
                'arrow down outline dark',
                'arrow up outline dark',
                'arrow-back',
                'circle-open',
                'circle-open-brick',
                'circle-open-fill-brick',
                'circle-open-small-brick',
                'circle-close',
                'circle-stroke-close-brick',
                'circle-stroke-open-brick',
                'circle-close-fill-brick',
                'arrow down dark in a circle',
                'arrow down dark in a circle medium',
                'info',
                'reset filter',
                'reset filter circle light',
                'arrow down dark small',
                'arrow up dark small',
                'smallPlan',
                'close-modal-small-light',
                'close-modal-large-light',
                'close-modal-large-transparent-gold',
                'header-logo',
                'compass dark',
                'compass-rotate',
                'visual panorama dark',
                'vk',
                'tg',
                'visual selection',
                'parameters selection',
                'water filter',
                'fire protection',
                'garbage sorting',
                'elevator',
                'people',
                'compass',
                'zoom plus dark large',
                'zoom minus dark large',
                'zoom plus transparent large',
                'zoom minus transparent large',
                'logo',
                'arrow down',
                'letter',
                'zoom plus dark circle',
                'zoom minus dark circle',
                'close modal square outline',
                'error notification circle',
                'step circle outline',
                'car circle outline',
                'step outline',
                'car outline',
                'vi logo',
                'plan locomotive',
                'plan kindergarten',
                'plan department',
                'plan workshop',
                'plan boulevard',
                'plan square',
                'encore logo',
                'encore logo dark',
                'pin',
                'small plan light',
                '6 ga',
                'forma team',
                'tsentsiper team',
                'gillespies team',
                'meganom team',
                '100',
                '5000',
                'evening',
                'day',
                'security system',
                'republic',
                'sun',
                'moon',
                'arrows',
                'infographics',
            ],
            control: {
                type: 'select',
            },
        },
    },
    decorators: [
        (story) => (
            <div className={'decorator'}>
                <div>
                    <Provider store={store}>{story()}</Provider>
                </div>
            </div>
        ),
    ],
} as ComponentMeta<typeof SvgIcons>;

// More on component templates: https://storybook.js.org/docs/react/writing-stories/introduction#using-args
const Template: ComponentStory<typeof SvgIcons> = (args) => <SvgIcons {...args} />;

export const SVG = Template.bind({});
// More on args: https://storybook.js.org/docs/react/writing-stories/args

SVG.args = {
    id: 'PDF in a circle',
} as ISvgIcons;
